services:
  - type: web
    name: elektronika
    env: python
    plan: free
    region: oregon
            buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
            startCommand: "python manage.py migrate && gunicorn elektronika.wsgi"    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: elektronika.settings
      - key: RENDER
        value: "true"
    autoDeploy: true
    disk:
      name: elektronika-data
      mountPath: /data
      sizeGB: 1

