services:
  - type: web
    name: elektronika
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: bash start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: elektronika.settings
    autoDeploy: true
    disk:
      name: elektronika-data
      mountPath: /data
      sizeGB: 1
